"""Public Python API for qerasure."""

from .code_utils import RotatedSurfaceCode
from .circuit_model_utils import (
    CompiledErasureProgram,
    ErasureCircuit,
    ErasureModel,
    OpCode,
    PauliChannel,
    SurfaceCodeRotated,
    StreamSampler,
    TQGSpreadModel,
    build_surface_code_erasure_circuit,
    compile_erasure_sampler,
)
from .lowering_utils import (
    LoweredErrorParams,
    LoweredEventOrigin,
    Lowerer,
    LoweringParams,
    LoweringResult,
    PauliError,
    PartnerSlot,
    SpreadProgram,
    SpreadInstruction,
    SpreadInstructionType,
    SpreadTargetOp,
    visualize_lowering,
)
from .noise_utils import NOISE_CHANNELS, NoiseChannel, NoiseParams
from .sim_utils import (
    ErasureQubitSelection,
    ErasureSimParams,
    ErasureSimResult,
    ErasureSimulator,
    EventType,
    visualize_erasures,
)
from .translation_utils import (
    build_logical_stabilizer_circuit,
    build_logical_stabilizer_circuit_object,
    build_logically_equivalent_erasure_stim_circuit,
    build_logically_equivalent_erasure_stim_circuit_object,
    build_surf_stabilizer_circuit,
    build_surface_code_stim_circuit,
)
from .virtual_translation_utils import (
    build_virtual_decoder_stim_circuit_conditioned,
    build_virtual_decoder_stim_circuit_conditioned_object,
    build_virtual_decoder_stim_circuit,
    build_virtual_decoder_stim_circuit_object,
    build_virtual_logical_stabilizer_circuit,
    build_virtual_logical_stabilizer_circuit_object,
)

__all__ = [
    "RotatedSurfaceCode",
    "OpCode",
    "PauliChannel",
    "TQGSpreadModel",
    "ErasureModel",
    "SurfaceCodeRotated",
    "ErasureCircuit",
    "CompiledErasureProgram",
    "StreamSampler",
    "build_surface_code_erasure_circuit",
    "compile_erasure_sampler",
    "NoiseChannel",
    "NoiseParams",
    "NOISE_CHANNELS",
    "EventType",
    "ErasureQubitSelection",
    "ErasureSimParams",
    "ErasureSimResult",
    "ErasureSimulator",
    "PauliError",
    "PartnerSlot",
    "SpreadInstructionType",
    "SpreadTargetOp",
    "SpreadProgram",
    "SpreadInstruction",
    "LoweredErrorParams",
    "LoweredEventOrigin",
    "LoweringParams",
    "LoweringResult",
    "Lowerer",
    "build_surf_stabilizer_circuit",
    "build_surface_code_stim_circuit",
    "build_logical_stabilizer_circuit",
    "build_logical_stabilizer_circuit_object",
    "build_logically_equivalent_erasure_stim_circuit",
    "build_logically_equivalent_erasure_stim_circuit_object",
    "build_virtual_decoder_stim_circuit_conditioned",
    "build_virtual_decoder_stim_circuit_conditioned_object",
    "build_virtual_decoder_stim_circuit",
    "build_virtual_decoder_stim_circuit_object",
    "build_virtual_logical_stabilizer_circuit",
    "build_virtual_logical_stabilizer_circuit_object",
    "visualize_erasures",
    "visualize_lowering",
]
